version: '3.9'
services:
  dill_bot:
    build: .
    restart: always
    command: python ./src/bot.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - ELEVENLABS_TOKEN=${ELEVENLABS_TOKEN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env 

  db:
    image: postgres:15
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dill_bot
      POSTGRES_DB: dill_bot_db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env