version: '3.9'
services:
  dill_bot:
    image: ./dill_bot
    restart: always
    volumes:
      - ./dill_bot/src:/src
    command: python /src/bot.py
    depends_on:
    - db
    - redis

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./dill_bot/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: <your-db-password>
      
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./dill_bot/redis:/data