name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Super Linter
        uses: github/super-linter@v4

      - name: Safety Check
        uses: pyupio/safety-ci@master
        env:
          TOKEN: ${{ secrets.PYUP_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.your-server.com/dill_do_bot:latest


      - name: Release Please
        uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          package-name: "dill_do_bot"

      - name: Notify local server
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_type: 'json'
          webhook_url: ${{ secrets.WEBHOOK_URL}}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        with:
          status: 'completed'